### ISSUE TITLE
dart2js --preview-dart-2 causing type error

### ISSUE THREAD

**Issue by jimmyff** [firebase/firebase-dart#179]
I'm getting the following error when I use the `--preview-dart-2` arg in my build file and building using `build_runner build`:

`EXCEPTION: TypeError: Closure 'DocumentSnapshot_getInstance': type '(DocumentSnapshotJsImpl) => DocumentSnapshot' is not a subtype of type '(dynamic) => DocumentSnapshot'`

I do not get this issue when using `build_runner serve`.

**Comment by kevmoo** [comment]
What's the codepath causing this? What firebase function are you calling?
Which version of the Dart SDK are you using?

**Comment by jimmyff** [comment]
@kevmoo Dart version __2.0.0-dev.63.0__

It looks like that `QuerySnapshot.get$docs` is the cause. Here is the full stack trace:

```
core_patch.dart:566 EXCEPTION: TypeError: Closure 'DocumentSnapshot_getInstance': type '(DocumentSnapshotJsImpl) => DocumentSnapshot' is not a subtype of type '(dynamic) => DocumentSnapshot'
STACKTRACE: 
TypeError: Closure 'DocumentSnapshot_getInstance': type '(DocumentSnapshotJsImpl) => DocumentSnapshot' is not a subtype of type '(dynamic) => DocumentSnapshot'
    at Object.wrapException (http://localhost:8000/main.dart.js:1088:17)
    at Object.functionTypeCheck (http://localhost:8000/main.dart.js:1724:17)
    at Interceptor.map$1$1 (http://localhost:8000/main.dart.js:16616:51)
    at Object.map$1$1$ax (http://localhost:8000/main.dart.js:3533:44)
    at QuerySnapshot.get$docs (http://localhost:8000/main.dart.js:62342:16)
    at Object.get$docs$x (http://localhost:8000/main.dart.js:3243:43)
    at http://localhost:8000/main.dart.js:61841:54
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8000/main.dart.js:3796:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:8000/main.dart.js:19900:12)
    at _awaitOnObject_closure.call$1 (http://localhost:8000/main.dart.js:19884:32)
    at NgZone__runUnary_closure.call$1 (http://localhost:8000/main.dart.js:34293:22)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:8000/main.dart.js:4374:18)
    at NgZone._runUnary$2$5 (http://localhost:8000/main.dart.js:34176:182)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:8000/main.dart.js:1455:14), <anonymous>:3:51)
    at _CustomZone.runUnary$2$2 (http://localhost:8000/main.dart.js:22680:182)
    at _Future__propagateToListeners_handleValueCallback.call$0 (http://localhost:8000/main.dart.js:20913:60)
    at Object._Future__propagateToListeners (http://localhost:8000/main.dart.js:4057:104)
    at _Future._completeWithValue$1 (http://localhost:8000/main.dart.js:20730:9)
    at _Future__asyncComplete_closure.call$0 (http://localhost:8000/main.dart.js:20832:10)
    at NgZone__scheduleMicrotask_closure.call$0 (http://localhost:8000/main.dart.js:34258:17)
    at NgZone__run_closure.call$0 (http://localhost:8000/main.dart.js:34275:26)
    at StaticClosure._rootRun [as call$1$4] (http://localhost:8000/main.dart.js:4359:16)
    at NgZone._run$1$4 (http://localhost:8000/main.dart.js:34162:158)
    at Object.eval (eval at Closure_forwardCallTo (http://localhost:8000/main.dart.js:1455:14), <anonymous>:3:47)
    at _CustomZone.run$1$1 (http://localhost:8000/main.dart.js:22671:158)
    at _CustomZone.runGuarded$1 (http://localhost:8000/main.dart.js:22591:14)
    at _CustomZone_bindCallbackGuarded_closure.call$0 (http://localhost:8000/main.dart.js:22824:25)
    at Object._microtaskLoop (http://localhost:8000/main.dart.js:4115:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:8000/main.dart.js:4121:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:8000/main.dart.js:19750:9)
    at invokeClosure (http://localhost:8000/main.dart.js:1279:26)
    at MutationObserver.<anonymous> (http://localhost:8000/main.dart.js:1299:18)
```

**Comment by kevmoo** [comment]
Pub upgrade. I fixed this yesterday. ☺️

**Comment by afpatmin** [comment]
I'm still getting warnings when streaming data from firestore database using DDC: `Cannot find native JavaScript type (firebase.firestore.DocumentChange) for type check` (firebase 4.5.1)

**Comment by kevmoo** [comment]
What method are you calling on firebase? I might have missed one...

**Comment by afpatmin** [comment]
I'm not 100% sure but I think it might be QuerySnapshot::docChanges()

**Comment by kevmoo** [comment]
Are you using `onSnapshot`, `onDocumentMetadataChanged`, or `onQueryMetadataChanged` ?

**Comment by afpatmin** [comment]
Yes I'm using onSnapshot

**Comment by afpatmin** [comment]
Another warning: `dart_sdk.js:4067 Cannot find native JavaScript type (firebase.storage.UploadTaskSnapshot) for type check` this warning is emitted when calling UploadTask.future (which is a Future<UploadTaskSnapshot>)

**Comment by kevmoo** [comment]
That is just the result of interip

**Comment by afpatmin** [comment]
Sorry, the complete call is;
```
final fb.StorageReference _logosRef = fb.storage().ref('logos');
...
await _logosRef
          .child(filename)
          .putString(data, 'base64', metadata)
          .future;
```

**Comment by kevmoo** [comment]
Could you try again w/ the v5 branch?

**Comment by kevmoo** [comment]
@afpatmin – warnings can be ignored here.

@jimmyff – any help reproducing?

**Comment by afpatmin** [comment]
Sorry to bother you but can I ignore all these warnings, or just the UploadTask ones? I tried using https://www.gstatic.com/firebasejs/5.1.0/firebase.js, along with a github dependency of firebase-dart, sdk: 2.0.0-dev.65.0, can confirm I'm still getting similar warnings: `Cannot find native JavaScript type (firebase.firestore.DocumentChange) for type check`

**Comment by jimmyff** [comment]
@kevmoo pub upgrade fixed my original issue. Thanks

**Comment by kevmoo** [comment]
@afpatmin – yup. You can ignore those warnings.

@jimmyff glad you're fixed!
